/**
 * The investor pages' share of site.css.
 *
 * The company stylesheet is 1,700 lines; the investor pages use its tokens,
 * its element rules and about ten of its classes. Parsing the rest on a
 * phone is main-thread work for nothing, so the build writes
 * `assets/css/invest-base.css`: the same source, cut to the rules these
 * pages can reach. One source of truth — the tokens cannot drift — and a
 * test holds that every class the pages use is defined in the subset.
 *
 * The parser is deliberately small: top-level blocks, `@media` recursed,
 * comments dropped. It understands the CSS this site writes, not all CSS.
 */

/** Classes from site.css the investor pages use. Prefixes: `btn` keeps `.btn--primary`, `.btn__arrow`. */
export const INVEST_BASE_CLASSES = ['btn', 'btn-row', 'eyebrow', 'faq-item', 'faq-list', 'on-ink', 'site-main', 'skip-link', 'visually-hidden', 'wordmark', 'star', 'js'];

/** Split a stylesheet into top-level blocks: { prelude, body, raw }. */
export function parseBlocks(css) {
  const src = css.replace(/\/\*[\s\S]*?\*\//g, '');
  const blocks = [];
  let depth = 0;
  let prelude = '';
  let body = '';
  for (let i = 0; i < src.length; i++) {
    const c = src[i];
    if (c === '{') {
      if (depth > 0) body += c;
      depth++;
    } else if (c === '}') {
      depth--;
      if (depth === 0) {
        blocks.push({ prelude: prelude.trim().replace(/\s+/g, ' '), body: body.trim() });
        prelude = '';
        body = '';
      } else body += c;
    } else if (depth === 0) prelude += c;
    else body += c;
  }
  return blocks;
}

function classRoot(name) {
  return name.replace(/(__|--).*$/, '');
}

/**
 * The selectors in a list that reach the investor pages, or an empty array.
 * A rule like `.site-header, .btn-row { display: none }` keeps only `.btn-row`.
 */
export function keptSelectors(prelude, keep) {
  return prelude
    .split(',')
    .map((s) => s.trim())
    .filter((sel) => {
      const classes = [...sel.matchAll(/\.([a-zA-Z_][\w-]*)/g)].map((m) => m[1]);
      if (!classes.length) return !/#/.test(sel); // element, pseudo and attribute rules are kept; id rules are not
      return classes.every((c) => keep.includes(classRoot(c)));
    });
}

/** Does any selector in the list reach the investor pages? */
export function selectorKept(prelude, keep) {
  return keptSelectors(prelude, keep).length > 0;
}

/** Render blocks back to CSS, recursing into @media / @supports. */
function render(blocks, keep) {
  const out = [];
  for (const b of blocks) {
    if (b.prelude.startsWith('@media') || b.prelude.startsWith('@supports')) {
      const inner = render(parseBlocks(b.body), keep);
      if (inner.trim()) out.push(`${b.prelude} {\n${indent(inner)}\n}`);
    } else if (b.prelude.startsWith('@')) {
      out.push(`${b.prelude} {\n${indent(b.body)}\n}`); // @font-face, @keyframes and the like: kept whole
    } else {
      const selectors = keptSelectors(b.prelude, keep);
      if (selectors.length) out.push(`${selectors.join(', ')} {\n${indent(b.body)}\n}`);
    }
  }
  return out.join('\n\n');
}

function indent(text) {
  return text
    .split('\n')
    .map((l) => (l.trim() ? `  ${l.trim()}` : ''))
    .join('\n');
}

export function subsetCss(css, { keep = INVEST_BASE_CLASSES } = {}) {
  const header = `/* Generated by the build from site.css — the rules the investor pages use. Edit site.css, not this file. */\n\n`;
  return header + render(parseBlocks(css), keep) + '\n';
}

/** Every class name a built HTML document uses, by root (`btn--primary` → `btn`). */
export function classesUsed(html) {
  const out = new Set();
  for (const m of html.matchAll(/\bclass="([^"]*)"/g)) {
    for (const c of m[1].split(/\s+/).filter(Boolean)) out.add(c);
  }
  return out;
}

/** Every class name a stylesheet defines (full names, not roots). */
export function classesDefined(css) {
  const out = new Set();
  for (const m of css.replace(/\/\*[\s\S]*?\*\//g, '').matchAll(/\.([a-zA-Z_][\w-]*)/g)) out.add(m[1]);
  return out;
}
